### ISSUE TITLE
Maize, probably and a (binary) classification problem

### ISSUE THREAD

**Issue by viv-analytics** [frankiethull/maize#13]
As initiated via X, I’m opening an issue: 

I'm curious about how the concept of {probably} plays into a (binary) classification scenario! I'd love to dive into an example case to see how it all comes together (detection, calibration, thresholding).
Can we exemplify this via {maize}?

**Comment by frankiethull** [comment]
I appreciate you reaching out, it helps me document the package and how it interacts with the rest of {tidymodels}! 

let's see if this helps out: 
https://github.com/frankiethull/maize/blob/main/vignettes/two-class-post-processing.qmd

Note, if you install the package this vignette should be pre-built in the /doc folder. First time I've done this but was testing how the latest release of {usethis} works with qmd vignettes and testing libraries in development. 

Additionally, I tried to go through some train, test, validation steps to show how I might explore the detection & thresholding with SVMs and {probably}. 

Lastly, and the coolest part about this, is {tailor}. Which masks some steps but think it's pretty slick depending on your use case. It's an experimental package that sits on top of {probably}, if you install the development version of {workflows} you can add a {tailor} object and adjust_*ments to your workflow similar to recipe step_*s.
